Leaf/blake/identify broncodirect page
BroncoDirectMe/Frontend pull request #36
Opened 2022-09-30 00:57 UTC by dal07065

Able to identify whether the current page is on BroncoDirect and identify whether the specific state of the page represent the Search Criteria page or Search Results Page

2022-09-30 08:03 UTC, alimomennasab commented
Looks good, cleaned up all of the excess comments and fixed the merging issues.

2022-09-30 08:05 UTC, alimomennasab commented
Looks good, cleaned up the excess comments and fixed the merging errors. (Accidentally closed the pr earlier, sorry!)

2022-09-30 08:08 UTC, alimomennasab reviewed
Looks good, cleaned up the excess comments and fixed the merging errors.

2022-09-30 08:20 UTC, alimomennasab approved these changes
Looks good, cleaned up the excess comments and fixed the merging errors.

2022-09-30 21:22 UTC, Leaversa commented on src/Content.tsx
> +    if (insts?.length == 0) console.log('- Enter Search Criteria Page');
```suggestion
    if (insts?.length === 0) console.log('- Enter Search Criteria Page');
```
it should be triple equals for the linter.

2022-09-30 21:22 UTC, Leaversa requested changes
I think you should consider using the header element text to determine which page is loaded rather than using the instructor elements. Since the header is always loaded on each page of BroncoDirect you're on you won't need to worry about bugs like if the elements doesn't load for whatever reason.

Here's some example code I wrote out that will get the title of the current page using this header method.
```
const iframe = document.getElementById('ptifrmtgtframe')
let header = iframe.contentWindow.document.querySelector('.gh-page-header-headings')
header.children[2].innerText
```

Other than that see my other comment about fixing the linting and your code should be good.

2022-10-01 18:22 UTC, dal07065 reviewed
Modified to use the header instead of the insts, professors list

2022-10-01 18:24 UTC, dal07065 reviewed
Reviewed

2022-10-01 18:26 UTC, dal07065 reviewed
Reviewed

2022-10-01 20:13 UTC, GuyWhoCode approved these changes

2022-10-02 07:05 UTC, Leaversa approved these changes

2022-10-03 04:58 UTC, merged