Simplify BroncoDirect Buttons
BroncoDirectMe/Frontend pull request #83
Opened 2023-03-30 22:13 UTC by GuyWhoCode

- Unifies RMP buttons into a single button with the professor's name as the button text
- Professor Popup now supports multiple professors and error handling if professors don't have a RMP page

2023-03-31 01:13 UTC, PattyCakesxD requested changes

2023-03-31 01:13 UTC, PattyCakesxD commented on src/ProfessorPopup.tsx
> +        setErrorMessage('This professor does not have a RateMyProfessor page.');
Indicate which professor caused this error for clarity (i.e., TBA/[insert professor here])
- e.g., The professor **Some Name** does not have a RateMyProfessor page.

If possible, try to put the entire text on 2 lines so the popup doesn't span a big length.
![image](https://user-images.githubusercontent.com/24869207/228996521-119c7703-728e-4b63-a0f2-a53a150b60dc.png)

2023-03-31 01:13 UTC, PattyCakesxD commented on src/RateMyProfessorButton.tsx
> +  // boxShadow: '0 0 8px rgba(0, 0, 0, 0.2)',
Do you still need these comments?

2023-03-31 01:13 UTC, PattyCakesxD commented on src/Content.tsx
>                  <ProfessorPopup professorName={inst.innerText} />
I can't find exactly where the culprit is, but courses with "To be Announced" have the text deleted in the professorpopup button

With extension:
![image](https://user-images.githubusercontent.com/24869207/228998079-47a8e283-f410-448c-826e-3a73ad7e3024.png)

Without:
![image](https://user-images.githubusercontent.com/24869207/228998116-f1564b9d-353c-40ab-a9eb-a7f47313efef.png)

2023-03-31 21:27 UTC, PattyCakesxD approved these changes

2023-04-01 20:36 UTC, Leaversa approved these changes

2023-04-02 03:04 UTC, merged